version: '2'
services:
    db:
      image: postgres:11.2
      container_name: nodepg_benchmarking
      ports:
        - "5436:5432"
      volumes:
        - ./pg_data:/data
      environment:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - PGDATA=/data
